
        CREATE TABLE IF NOT EXISTS power_plants (
            id SERIAL PRIMARY KEY,
            "OBJECTID" INTEGER, "PLANT_CODE" TEXT, "NAME" TEXT, "ADDRESS" TEXT, "CITY" TEXT, "STATE" TEXT, "ZIP" TEXT, "TELEPHONE" TEXT, "TYPE" TEXT, "STATUS" TEXT, "COUNTY" TEXT, "COUNTYFIPS" TEXT, "COUNTRY" TEXT, "LATITUDE" NUMERIC, "LONGITUDE" NUMERIC, "NAICS_CODE" TEXT, "NAICS_DESC" TEXT, "SOURCE" TEXT, "SOURCEDATE" TEXT, "VAL_METHOD" TEXT, "VAL_DATE" TEXT, "WEBSITE" TEXT, "OPERATOR" TEXT, "OPERAT_ID" TEXT, "OPER_CAP" INTEGER, "SUMMER_CAP" NUMERIC, "WINTER_CAP" NUMERIC, "PLAN_CAP" INTEGER, "RETIRE_CAP" INTEGER, "GEN_UNITS" INTEGER, "PLAN_UNIT" INTEGER, "RETIR_UNIT" INTEGER, "PRIM_FUEL" TEXT, "SEC_FUEL" TEXT, "COAL_USED" INTEGER, "NGAS_USED" INTEGER, "OIL_USED" INTEGER, "NET_GEN" INTEGER, "CAP_FACTOR" NUMERIC, "SUB_1" TEXT, "SUB_2" TEXT, "LINES" INTEGER, "SOURCE_LAT" NUMERIC, "SOURC_LONG" NUMERIC,
            geom GEOMETRY(POINT, 4326)
        );
        