[project]
name = "rcac"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "contextily>=1.6.2",
    "folium>=0.19.5",
    "geopandas>=1.0.1",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "psycopg2>=2.9.10",
    "tabulate>=0.9.0",
]
